### ISSUE TITLE
Other issue i fixed alo but this

### ISSUE THREAD

**Issue by Nangyalashraf** [protyodev/botmanager#2]
GETTING STATS
[WS => Shard 0] Heartbeat acknowledged, latency of 553ms.
Error: connect ECONNREFUSED 127.0.0.1:22
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 22,
  level: 'client-socket'
}
finished:  234  | Which was my:  1 . Server
DiscordAPIError: Unknown Channel
    at RequestHandler.execute (C:\Users\Barya\Desktop\botmanager-main\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Barya\Desktop\botmanager-main\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async ChannelManager.fetch (C:\Users\Barya\Desktop\botmanager-main\node_modules\discord.js\src\managers\ChannelManager.js:115:18) {
  method: 'get',
  path: '/channels/948222855366189076',
  code: 10003,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}

**Comment by protyodev** [comment]
Change IDs correclty

**Comment by Nangyalashraf** [comment]
I have change but what is node modules error?

**Comment by protyodev** [comment]
You have something called google?

**Comment by Nangyalashraf** [comment]
i have what does this error means i went to file but nothing id channel 
![image](https://user-images.githubusercontent.com/103633643/163825152-d78ce09b-1a72-4c29-a393-317f52713094.png)

**Comment by protyodev** [comment]
If you changed the IDs correctly then idk JUST IGNORE it i have it as well it's DISCORD API NOT PROTYO BOT MANAGER

**Comment by Nangyalashraf** [comment]
when i went to file thier is no id like that

**Comment by Nangyalashraf** [comment]
![image](https://user-images.githubusercontent.com/103633643/163825799-2eb265ad-c6e5-424f-b4a5-763dc536f5f0.png)
now mad on the errors

**Comment by protyodev** [comment]
Dude put in your VPS 234 is mine, it won't work then. And just ignore DiscordAPI error it's not causing any troubles jesus.

**Comment by Nangyalashraf** [comment]
I don't have vps thier are many free hosting panels

**Comment by protyodev** [comment]
idk about free hosting

**Comment by protyodev** [comment]
just buy a vps it won't work on free hosting
