### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gamerdave08** [protyodev/botmanager#3]
![image](https://user-images.githubusercontent.com/103964866/163890494-2c8d607e-e839-4d9f-ac75-4580fcb43ea8.png)

**Comment by protyodev** [comment]
Change the guild ID line 53

**Comment by gamerdave08** [comment]
commands.js?

**Comment by protyodev** [comment]
Jesus read in which file the error is.
**OrderSystem.js**

**Comment by gamerdave08** [comment]
der bot hat wieder errors


![image](https://user-images.githubusercontent.com/103964866/163968080-1ae7eb9d-3c39-4c99-b163-a50f3a8bebed.png)

**Comment by protyodev** [comment]
Mach doch keine Issues auf wenn du zu lostbist die IDs zu ändern.
